### PR TITLE
Fix DiscoveryClient functionality

### PR DESCRIPTION
**Pull request by dimatomp**
Fix for #70.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@keveleigh, @jwittner, @NeerajW, @mrbobbybobberson, could we get some eyes on this and have it recompiled for HoloToolkit-Unity?  Pretty excited to see this fix soon.

**Comment by christjt** [comment]
Bump, please review this PR 👍

**Comment by keveleigh** [comment]
Is this a re-adding of code that was removed in #69, or is this new code? Also, some comments to help me understand what this code is doing and why it's needed would be greatly appreciated :) I understand that this fixes discovery, but I can't seem to wrap my head around exactly how haha.

**Comment by dimatomp** [comment]
@keveleigh I have found no files containing 'Discovery' substring in that PR. The only re-added line enables `ProfileManager` on server side - it was commented in #69.
For explanation of the change, see:
* http://www.jenkinssoftware.com/raknet/manual/revisionlog.html
* https://github.com/facebookarchive/RakNet/blob/master/Source/RakPeer.cpp#L1491
* https://github.com/facebookarchive/RakNet/blob/master/Source/RakNetDefines.h#L179 
* https://github.com/Microsoft/HoloToolkit/blob/master/Sharing/Src/External/RakNet-4.081/src/Source/RakPeer.h#L640

Looks like `RAKPEER_USER_THREADED` macro had been introduced in the RakNet update but this change was not reflected here. One needed to call `RunUpdateCycle(...)` before doing `Receive()` to see the new messages.
I came up with this solution via native library debugging in VS. Basically, there were two buffers for incoming messages in RakPeer implementation and `Receive()` was trying to retrieve a ping response from the wrong one.

**Comment by NeerajW** [comment]
Who will update binaries?

**Comment by dimatomp** [comment]
It's all right, I am not going to add any more minor fixes. You may merge it already 😆

**Comment by romsahel** [comment]
@dimatomp Thanks for your fixes, it works almost perfectly on my end.
I am still getting an error though, when I'm running both the server and the client on the same machine, saying the error 20605 is already opened.
In `ProfileManagerImpl`'s constructor (in `Sharing/Src/Source/Common/Private/ProfileManagerImpl.cpp`, line 32), the lines 68-69 seem to be opening the server's discovery port no matter what the given role is:
`m_discoveryResponseReceipt = m_socketMgr->AcceptDiscoveryPings(kDiscoveryServerPort, role);`.

Shouldn't it be moved to inside the switch's case `XTools::SessionDiscoveryServerRole`?

Here's a patch file of what fixes the problem on my end: [0001-Discovery-Fix-client-opening-server-discovery-port.txt](https://github.com/Microsoft/HoloToolkit/files/1182734/0001-Discovery-Fix-client-opening-server-discovery-port.txt)

**Comment by dimatomp** [comment]
@romsahel Thanks for the patch, I will take a look and solve the problem today.

**Comment by StephenHodgson** [comment]
@NeerajW When this gets approved and merged I'll update the binaries and submit a PR on HTK (MRTK).

**Comment by StephenHodgson** [comment]
@dimatomp & @romsahel thanks for all the hard work!  You guys think this is ready?  Still need to test this out myself to make sure it works.

**Comment by romsahel** [comment]
@StephenHodgson I've been using this patch in Unity (with the Holotoolkit-Unity) for the past few days with no problem!

**Comment by dimatomp** [comment]
Maybe it also would be reasonable to check that all packets from all discovered servers are processed. But the feature appears to be working in general.

**Comment by StephenHodgson** [comment]
Tried pulling your branch today and ran BuildAll.bat but ran into this error about RakNet:
image

**Comment by StephenHodgson** [comment]
Ah yes, it's because I do not have visual studio 2015 installed. Sorry.

**Comment by markgrossnickle** [comment]
Any reason this hasn't been brought into the main branch?

**Comment by StephenHodgson** [comment]
It hasn't been approved and merged in the HoloToolkit repo

**Comment by markgrossnickle** [comment]
@StephenHodgson Right, but it appears to have been approved by 2 reviewers on July 19th.  Are we waiting on a 3rd reviewer that we need to nudge? Or what is the next step?

I grabbed his branch, built, and tested and it works for me.  I know many others are frustrated by this bug though.  Mainly speaking up to make sure its not forgotten about since that appears to be the case.

**Comment by StephenHodgson** [comment]
It's approved, but I don't have power there to merge.  It'll have to be one of the contributors there.

**Comment by keveleigh** [comment]
Merged! We're looking into getting DLLs officially signed before we migrate these changes over the MixedRealityToolkit-Unity, so that's been part of the hold up as well.

**Comment by StephenHodgson** [comment]
Thanks!

**Comment by sebrk** [comment]
Sorry for a bit off topic but this might help me anyway because the auto discovery is using UNET in the toolkit. I'm using the same NetworkDiscovery to broadcast UDP packets in order to auto setup a number of devices. I'm not going to be sending more than a few bytes every now and then to change scenes etc. However the Hololens does not answer UDP and it does not even send UDP. Does my issues relate to this issue or is it simply so that the Hololens does not support UDP protocol? I can clearly see my packets on the network and it works flawless on other devices (UWP or mobile).

Again, sorry for off topic but I would very much like to know if this is a hardware bug, something intentional or a bug down the line the code chain?

**Pull request merged**
